Repository AY2021S2-CS2103-W17-1/tp, pull requests merged in 2021-03, with the labels that each got.

#56 Add functionality to create plans and semester
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPlanCommand.java
  src/main/java/seedu/address/logic/commands/AddSemesterCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/InfoCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddPlanCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSemesterCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/plan/Description.java
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedPlan.java
  src/main/java/seedu/address/storage/JsonAdaptedSemester.java
  src/main/java/seedu/address/storage/JsonPlansStorage.java
  src/main/java/seedu/address/storage/JsonSerializablePlans.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddPlanCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPlanCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/DescriptionBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/DescriptionBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
  src/test/java/seedu/address/model/person/PlanTest.java
  src/test/java/seedu/address/model/person/UniquePlanListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPlanTest.java
  src/test/java/seedu/address/storage/JsonDescriptionBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableDescriptionBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/PlanBuilder.java
  src/test/java/seedu/address/testutil/PlanUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalPlans.java
Labels: priority.High

#61 Add functionality to delete semesters
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddPlanCommand.java
  src/main/java/seedu/address/logic/commands/AddSemesterCommand.java
  src/main/java/seedu/address/logic/commands/DeletePlanCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSemesterCommand.java
  src/main/java/seedu/address/logic/parser/AddPlanCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSemesterCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePlanCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteSemesterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/model/plan/Semester.java
  src/test/java/seedu/address/logic/commands/AddPlanCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPlanCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, type.Story

#64 Update UI for plans
  src/main/java/seedu/address/logic/commands/DeleteSemesterCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PlanCard.java
  src/main/java/seedu/address/ui/PlanListPanel.java
  src/main/resources/view/PlanListCard.fxml
  src/main/resources/view/PlanListPanel.fxml
Labels: priority.High, type.Task

#57 Add history, current semester, master plan
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CurrentSemesterCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/MasterPlanCommand.java
  src/main/java/seedu/address/logic/commands/ShowCapCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/commands/ShowMcCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CurrentSemesterCommandParser.java
  src/main/java/seedu/address/logic/parser/MasterPlanCommandParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/plan/Module.java
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/model/plan/Semester.java
  src/main/java/seedu/address/model/util/History.java
  src/main/java/seedu/address/storage/JsonAdaptedPlan.java
  src/main/java/seedu/address/storage/JsonSerializablePlans.java
Labels: priority.High, type.Story

#71 JUnit testing for Plan and Description
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PlanTest.java
  src/test/java/seedu/address/model/plan/DescriptionTest.java
  src/test/java/seedu/address/model/plan/PlanTest.java
  src/test/java/seedu/address/testutil/TypicalPlans.java
  src/test/resources/view/UiPartTest/validFile.fxml
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: priority.Medium, type.Task

#72 Update user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#69 UI info
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddPlanCommand.java
  src/main/java/seedu/address/logic/commands/InfoCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/InfoCard.java
  src/main/java/seedu/address/ui/InfoListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#77 add validate command and some javafx stuff for plan
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/MasterPlanCommand.java
  src/main/java/seedu/address/logic/commands/ValidateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/model/plan/Semester.java
  src/main/java/seedu/address/ui/PlanCard.java
Labels: priority.High

#81 V1.2 bugfixes
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MasterPlanCommand.java
  src/main/java/seedu/address/logic/commands/ValidateCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/plan/Module.java
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/ui/PlanCard.java
Labels: priority.High, type.Bug

#86 Add TableView for list javafx
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/storage/JsonAdaptedPlan.java
  src/main/java/seedu/address/ui/PlanCard.java
  src/main/java/seedu/address/ui/PlanListPanelWithTable.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PlanListCard.fxml
  src/main/resources/view/PlanListPanelWithTable.fxml
  src/main/resources/view/PlanListPanel_BAK.fxml
Labels: priority.High

#94 Fix missing/empty moduleinfo.json bug
  build.gradle
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/ui/PlanCard.java
Labels: priority.High, severity.High

#96 Complete JUnit testing for Add/Delete Plan & Semester commands
  src/main/java/seedu/address/logic/commands/AddSemesterCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeletePlanCommand.java
  src/main/java/seedu/address/logic/commands/ValidateCommand.java
  src/main/java/seedu/address/model/plan/DescriptionContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddPlanCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSemesterCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePlanCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSemesterCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/plan/DescriptionTest.java
  src/test/java/seedu/address/model/plan/PlanTest.java
  src/test/java/seedu/address/testutil/PlanBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPlans.java
Labels: priority.High, severity.Low

#99 Add Semester & UniquePlanList JUnit testing
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/plan/Semester.java
  src/main/java/seedu/address/model/plan/UniquePlanList.java
  src/main/java/seedu/address/model/plan/exceptions/DuplicatePlanException.java
  src/main/java/seedu/address/model/plan/exceptions/PlanNotFoundException.java
  src/test/java/seedu/address/model/plan/SemesterTest.java
  src/test/java/seedu/address/model/plan/UniquePlanListTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalSemesters.java
Labels: priority.High, severity.Low, type.Task

#101 Enable assertions for gradle build
  build.gradle
Labels: priority.High, severity.High, type.Task

#102 V1.3 junit
  build.gradle
  src/main/java/seedu/address/logic/commands/ValidateCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/ValidateCommandTest.java
Labels: priority.High

#104 clean up and add javafx tables for list command
  src/main/java/seedu/address/model/plan/Plan.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PlanListPanelWithTable.java
  src/main/resources/view/PlanListPanelWithTable.fxml
Labels: priority.High, type.Enhancement

#117 Update Add Plan Command in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddPlanArchitectureSequenceDiagram.puml
  docs/diagrams/PlanConstructorSequenceDiagram.puml
  docs/diagrams/PlanObjectDiagram.puml
  docs/diagrams/PlanToStringSequenceDiagram.puml
  docs/images/AddPlanArchitectureSequenceDiagram.png
  docs/images/AddPlanObjectDiagram.png
  docs/images/PlanConstructorSequenceDiagram.png
  docs/images/PlanToStringSequenceDiagram.png
  src/test/java/seedu/plan/logic/commands/AddSemesterCommandTest.java
  src/test/java/seedu/plan/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/plan/testutil/TypicalPlans.java
Labels: priority.High, severity.Low, type.Task

#122 Add example output with screenshots in User Guide
  docs/UserGuide.md
  docs/images/AddPlan.png
  docs/images/AddSemester.png
  docs/images/DeletePlan.png
  docs/images/DeleteSemester.png
Labels: priority.High, severity.VeryLow, type.Task

#116 fix javafx null pointer except
  build.gradle
  src/main/java/seedu/plan/ui/PlanListPanelWithTable.java
  src/main/resources/view/PlanListPanelWithTable.fxml
Labels: severity.VeryLow, type.Bug

#129 UG update add all examples
  docs/UserGuide.md
  docs/images/UiLanding.png
  docs/images/exampleHistory.png
  docs/images/listPlans.png
Labels: type.Task

#132 Update Landing Page
  docs/index.md
Labels: priority.Low, severity.Low, type.Task

#133 fix a bug with storage not updating when using validate
  src/main/java/seedu/plan/model/ModelManager.java
  src/main/java/seedu/plan/ui/PlanListPanelWithTable.java
Labels: type.Bug

#134 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Low, severity.Low
