Repository AY2021S2-CS2103-W17-1/tp, pull requests merged in 2021-04, with the labels that each got.

#206 Fix error message bug in MasterCommand
  src/main/java/seedu/plan/logic/commands/MasterPlanCommand.java
  src/test/java/seedu/plan/logic/commands/DeleteSemesterCommandTest.java
Labels: priority.Medium, severity.Low, type.Bug

#207 Fix error message bug in CurrentSemesterCommand
  src/main/java/seedu/plan/logic/commands/CurrentSemesterCommand.java
Labels: priority.Medium, severity.Low, type.Bug

#208 Fix several documentation bugs in UG
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, type.Bug

#209 Fix error message bugs for Description & Tag
  src/main/java/seedu/plan/model/plan/Description.java
  src/main/java/seedu/plan/model/tag/Tag.java
Labels: priority.Medium, severity.Medium, type.Bug

#210 Fix add plan command example bug
  src/main/java/seedu/plan/logic/commands/AddPlanCommand.java
Labels: priority.Medium, severity.Medium, type.Bug

#217 Add CS1010 & CS1010S to module list
  src/main/java/seedu/plan/model/ModulePlanner.java
Labels: priority.Medium, severity.Medium, type.Bug

#218 Fix bug where Plan description is not unique
  src/main/java/seedu/plan/model/ModulePlanner.java
  src/test/java/seedu/plan/logic/commands/AddPlanCommandTest.java
Labels: priority.Medium, severity.High, type.Bug

#219 Enforce valid semester number to be added
  src/main/java/seedu/plan/commons/core/Messages.java
  src/main/java/seedu/plan/logic/commands/AddSemesterCommand.java
  src/main/java/seedu/plan/model/ModulePlanner.java
Labels: priority.Medium, severity.High, type.Bug

#220 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Low, severity.Low, type.Bug

#221 Update UG link in help window
  src/main/java/seedu/plan/ui/HelpWindow.java
Labels: priority.Medium, severity.Low

#223 1.4 bugfixes
  docs/UserGuide.md
Labels: priority.High, type.Bug

#225 resolve bugs related to GUI resize
  src/main/java/seedu/plan/ui/MainWindow.java
Labels: type.Bug

#237 Minor refactoring
  src/main/java/seedu/plan/MainApp.java
  src/main/java/seedu/plan/logic/commands/ValidateCommand.java
Labels: priority.Low, severity.Low, type.Bug

#245 Update Sean's Portfolio Page
  docs/team/seaniy.md
Labels: priority.High
